services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: thatsitag10/frontend:latest
    ports:
      - '8501:8501'
    depends_on:
      - convert
      - password
      - merge
    networks:
      - app-network

  convert:
    build:
      context: ./convert
      dockerfile: Dockerfile
    container_name: convert
    image: thatsitag10/convert:latest
    ports:
      - '8000:8000'
    networks:
      - app-network

  password:
    build:
      context: ./protect
      dockerfile: Dockerfile
    container_name: password
    image: thatsitag10/password:latest
    ports:
      - '8001:8001'
    networks:
      - app-network

  merge:
    build:
      context: ./merge
      dockerfile: Dockerfile
    container_name: merge
    image: thatsitag10/merge:latest
    ports:
      - '8002:8002'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
