apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8501
      - path: /convert
        pathType: Prefix
        backend:
          service:
            name: convert-service
            port:
              number: 8000
      - path: /password
        pathType: Prefix
        backend:
          service:
            name: password-service
            port:
              number: 8001
      - path: /merge
        pathType: Prefix
        backend:
          service:
            name: merge-service
            port:
              number: 8002